# Generated by Django 4.1.4 on 2023-02-06 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_account_bid_dispute_job_message_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
