# Generated by Django 4.1.4 on 2023-02-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_send_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_at',
            new_name='sent_at',
        ),
    ]
