# Generated by Django 4.1.4 on 2025-06-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
